### ISSUE TITLE
Userinfo Command.

### ISSUE THREAD

**Issue by Josia50** [Sontles/YugoBot#1]
When you do .userinfo it reacts fine, but it also reacts to like +userinfo,>userinfo,-userinfo.

I take this is since no prefix has been defined in config. .slice(1) takes away the first and reads userinfo.

Simple fix , Add a prefix in config.

**Comment by Sontles** [comment]
Josia! Thanks mate! Will do that, though im gonna start on a new bot soon, so yeah.. I'll do it some time soon
